import { auth } from '@/auth';
import { supabaseAdmin } from '@/lib/supabase/admin';

/**
 * Server-side data fetchers to avoid unnecessary API calls and client-side useEffect
 * These functions run on the server and return pre-fetched data to components
 */

export async function fetchUserProfile() {
  const session = await auth();
  if (!session?.user?.id) return null;

  const oauthName = session.user.name ?? null;
  const emailPrefix = session.user.email?.split('@')[0] ?? null;

  const { data: profiles, error } = await supabaseAdmin
    .from('profiles')
    .select('display_name, streak_count, telegram_id')
    .eq('id', session.user.id)
    .limit(1);

  if (error || !profiles?.[0]) {
    return {
      display_name: oauthName || emailPrefix || 'User',
      streak_count: 0,
      telegram_id: null,
    };
  }

  const profile = profiles[0];

  // Auto-correct display names that were generated from email prefix or UUID slice,
  // replacing them with the real OAuth name when available.
  const storedName = profile.display_name ?? '';
  const looksAutoGenerated =
    !storedName ||
    (emailPrefix !== null && storedName === emailPrefix) ||
    /^[0-9a-f]{8}$/i.test(storedName);

  if (oauthName && looksAutoGenerated) {
    profile.display_name = oauthName;
    // Persist correction to DB so subsequent loads use the real name
    void supabaseAdmin
      .from('profiles')
      .update({ display_name: oauthName })
      .eq('id', session.user.id);
  }

  return profile;
}

export async function fetchUserThemes() {
  const session = await auth();
  if (!session?.user?.id) return [];

  const { data, error } = await supabaseAdmin
    .from('themes')
    .select('*')
    .eq('user_id', session.user.id)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Failed to fetch themes:', error);
    return [];
  }

  return data ?? [];
}

export async function fetchUserStreak() {
  const session = await auth();
  if (!session?.user?.id) return 0;

  const { data: profiles, error } = await supabaseAdmin
    .from('profiles')
    .select('streak_count')
    .eq('id', session.user.id)
    .limit(1);

  if (error || !profiles?.[0]) return 0;
  return profiles[0].streak_count ?? 0;
}

export async function fetchStudySession(themeId: string) {
  const session = await auth();
  if (!session?.user?.id) return null;

  const { data: sessions, error } = await supabaseAdmin
    .from('sessions')
    .select('*')
    .eq('theme_id', themeId)
    .eq('user_id', session.user.id)
    .order('created_at', { ascending: false })
    .limit(1);

  if (error) {
    console.error('Failed to fetch study session:', error);
    return null;
  }
  return sessions?.[0] ?? null;
}

export async function fetchStudyCards(sessionId: string, limit: number = 50) {
  const { data, error } = await supabaseAdmin
    .from('cards')
    .select('*')
    .eq('study_session_id', sessionId)
    .order('created_at', { ascending: true })
    .limit(limit);

  if (error) {
    console.error('Failed to fetch cards:', error);
    return [];
  }

  return data ?? [];
}

export async function fetchDataSources(themeId: string) {
  const session = await auth();
  if (!session?.user?.id) return [];

  const { data, error } = await supabaseAdmin
    .from('data_sources')
    .select('*')
    .eq('theme_id', themeId)
    .eq('user_id', session.user.id)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Failed to fetch sources:', error);
    return [];
  }

  return data ?? [];
}

export async function fetchTheme(themeId: string) {
  const session = await auth();
  if (!session?.user?.id) {
    return null;
  }

  const { data: themes, error } = await supabaseAdmin
    .from('themes')
    .select('*')
    .eq('id', themeId)
    .eq('user_id', session.user.id)
    .limit(1);

  if (error) {
    console.error('fetchTheme: Supabase error', { themeId, error });
    return null;
  }

  if (!themes?.[0]) {
    console.error('fetchTheme: Theme not found', {
      themeId,
      userId: session.user.id,
      resultCount: themes?.length,
    });
    return null;
  }

  console.log('fetchTheme: Success', { themeId, themeName: themes[0].name });
  return themes[0];
}
